const COMMENTS = {
    FETCH: 'FETCH_COMMENTS_LOAD',
    FETCH_SUCCESS: 'FETCH_COMMENTS_SUCCESS',
    FETCH_FAILURE: 'FETCH_COMMENTS_FAILURE',

    POST: 'POST_COMMENTS_LOAD',
    POST_SUCCESS: 'POST_COMMENTS_SUCCESS',
    POST_FAILURE: 'POST_COMMENTS_FAILURE'
}

export default COMMENTS;